FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY backend/package.json backend/package-lock.json* ./

# Install dependencies
RUN npm install
# Copy the rest of the code
COPY backend/ ./

# Expose the port the app runs on
EXPOSE 3001

# Command to run the app
CMD ["npm", "start"]