version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING}
    # Pas de dépendance de db ici
    # depends_on:
    #   - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge